In [ ]:
import pandas as pd

movies=pd.read_csv("movies.csv")



In [ ]:
movies

movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
62418   209157                           We (2018)   
62419   209159           Window of the Soul (2001)   
62420   209163                    Bad Poems (2018)   
62421   209169                 A Girl Thing (2001)   
62422   209171      Women of Devil's Island (1962)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
62418                                        Drama  
62419                                  Documentary  
62420                                 Comedy|Drama  
62421                           (no genres listed)  
62422                       Action|Adventure|Drama  

[62423 rows x 3 columns]

In [ ]:
import re

def clean_title(title):
  return re.sub("[^a-zA-Z0-9 ]", "", title)



In [ ]:
movies["clean_title"] = movies["title"].apply(clean_title)

In [ ]:
movies


movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
62418   209157                           We (2018)   
62419   209159           Window of the Soul (2001)   
62420   209163                    Bad Poems (2018)   
62421   209169                 A Girl Thing (2001)   
62422   209171      Women of Devil's Island (1962)   

                                            genres  \
0      Adventure|Animation|Children|Comedy|Fantasy   
1                       Adventure|Children|Fantasy   
2                                   Comedy|Romance   
3                             Comedy|Drama|Romance   
4                                           Comedy   
...                                            ...   
62418                                        Drama   
62419                                  Documentary   
62420                                 Comedy|Drama   
62421                           (no genres listed)   
62422                       Action|Adventure|Drama   

                            clean_title  
0                        Toy Story 1995  
1                          Jumanji 1995  
2                 Grumpier Old Men 1995  
3                Waiting to Exhale 1995  
4      Father of the Bride Part II 1995  
...                                 ...  
62418                           We 2018  
62419           Window of the Soul 2001  
62420                    Bad Poems 2018  
62421                 A Girl Thing 2001  
62422       Women of Devils Island 1962  

[62423 rows x 4 columns]

Vectorization for creating tfid matrix


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range=(1,2))

tfidf=vectorizer.fit_transform(movies["clean_title"])

Search fn.

In [ ]:
# !pip install sklearn

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def search(title):
  
  title = clean_title(title)
  query_vec=vectorizer.transform([title])
  similarity = cosine_similarity(query_vec,tfidf).flatten()
  indices= np.argpartition(similarity, -5)[-5:]
  #reverse the list
  results=movies.iloc[indices][::-1]  
  return results

In [ ]:
query_vec

<1x170073 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [ ]:
similarity

array([1.        , 0.09681098, 0.06531543, ..., 0.        , 0.        ,
       0.        ])

In [ ]:
indices

array([20497, 14813, 59767,  3021,     0])

In [ ]:
results

movieId                       title  \
0            1            Toy Story (1995)   
3021      3114          Toy Story 2 (1999)   
59767   201588          Toy Story 4 (2019)   
14813    78499          Toy Story 3 (2010)   
20497   106022  Toy Story of Terror (2013)   

                                                 genres  \
0           Adventure|Animation|Children|Comedy|Fantasy   
3021        Adventure|Animation|Children|Comedy|Fantasy   
59767               Adventure|Animation|Children|Comedy   
14813  Adventure|Animation|Children|Comedy|Fantasy|IMAX   
20497                         Animation|Children|Comedy   

                    clean_title  
0                Toy Story 1995  
3021           Toy Story 2 1999  
59767          Toy Story 4 2019  
14813          Toy Story 3 2010  
20497  Toy Story of Terror 2013

In [ ]:
import ipywidgets as widgets
from IPython.display import display

movie_input= widgets.Text(
    value="Toy Story",
    description="Movie Title:",
    disabled=False
)

movie_list=widgets.Output()
def on_type(data):
  with movie_list:
    movie_list.clear_output()
    title=data["new"]
    if len(title) > 5:
      display(search(title))

movie_input.observe(on_type, names='value')
display(movie_input, movie_list)
# movie_input

Text(value='Toy Story', description='Movie Title:')

Output()

In [ ]:
ratings=pd.read_csv("ratings.csv")
ratings

userId  movieId  rating   timestamp
0              1      296     5.0  1147880044
1              1      306     3.5  1147868817
2              1      307     5.0  1147868828
3              1      665     5.0  1147878820
4              1      899     3.5  1147868510
...          ...      ...     ...         ...
25000090  162541    50872     4.5  1240953372
25000091  162541    55768     2.5  1240951998
25000092  162541    56176     2.0  1240950697
25000093  162541    58559     4.0  1240953434
25000094  162541    63876     5.0  1240952515

[25000095 rows x 4 columns]

In [ ]:
ratings.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [ ]:
# movie_id= 1

In [ ]:
similar_users= ratings[(ratings["movieId"] == movie_id) & (ratings["rating"] > 4)]["userId"].unique()

In [ ]:
similar_users

array([    36,     75,     86, ..., 162527, 162530, 162533])

In [ ]:
similar_users_rec= ratings[(ratings["userId"].isin(similar_users)) & (ratings["rating"] > 4)]["movieId"]

In [ ]:
similar_users_rec

5101            1
5105           34
5111          110
5114          150
5127          260
            ...  
24998854    60069
24998861    67997
24998876    78499
24998884    81591
24998888    88129
Name: movieId, Length: 1358326, dtype: int64

In [ ]:
similar_user_recs=similar_users_rec.value_counts()/len(similar_users)
similar_user_recs=similar_user_recs[similar_user_recs > .1]

In [ ]:
similar_user_recs

1        1.000000
318      0.445607
260      0.403770
356      0.370215
296      0.367295
           ...   
953      0.103053
551      0.101195
1222     0.100876
745      0.100345
48780    0.100186
Name: movieId, Length: 113, dtype: float64

In [ ]:
all_users = ratings[(ratings["movieId"].isin(similar_user_recs.index)) & (ratings["rating"] > 4)]

In [ ]:
all_users_recs=all_users["movieId"].value_counts()/len(all_users["userId"].unique())

In [ ]:
all_users_recs

318      0.342220
296      0.284674
2571     0.244033
356      0.235266
593      0.225909
           ...   
551      0.040918
50872    0.039111
745      0.037031
78499    0.035131
2355     0.025091
Name: movieId, Length: 113, dtype: float64

In [ ]:
recs_percentages=pd.concat([similar_user_recs, all_users_recs], axis=1)
recs_percentages.columns=["similar","all"]

In [ ]:
recs_percentages

similar       all
1      1.000000  0.124728
32     0.160711  0.100293
34     0.130555  0.052229
47     0.225909  0.144469
50     0.275604  0.200513
...         ...       ...
59315  0.104593  0.054269
60069  0.170640  0.076307
68954  0.159172  0.064944
78499  0.152960  0.035131
79132  0.166817  0.131384

[113 rows x 2 columns]

In [ ]:
recs_percentages["score"]=recs_percentages["similar"]/recs_percentages["all"]

In [ ]:
recs_percentages =recs_percentages.sort_values("score", ascending=False)

In [ ]:
recs_percentages

similar       all     score
1      1.000000  0.124728  8.017414
3114   0.280648  0.053706  5.225654
2355   0.110539  0.025091  4.405452
78499  0.152960  0.035131  4.354038
4886   0.235147  0.070811  3.320783
...         ...       ...       ...
2858   0.216724  0.167634  1.292845
296    0.367295  0.284674  1.290232
79132  0.166817  0.131384  1.269693
4973   0.142501  0.112405  1.267747
2959   0.262649  0.216717  1.211946

[113 rows x 3 columns]

In [ ]:
recs_percentages.head(10).merge(movies,left_index=True,right_on="movieId")

similar       all     score  movieId                        title  \
0      1.000000  0.124728  8.017414        1             Toy Story (1995)   
3021   0.280648  0.053706  5.225654     3114           Toy Story 2 (1999)   
2264   0.110539  0.025091  4.405452     2355         Bug's Life, A (1998)   
14813  0.152960  0.035131  4.354038    78499           Toy Story 3 (2010)   
4780   0.235147  0.070811  3.320783     4886        Monsters, Inc. (2001)   
580    0.216618  0.067513  3.208539      588               Aladdin (1992)   
6258   0.228139  0.072268  3.156862     6377          Finding Nemo (2003)   
587    0.179400  0.059977  2.991150      595  Beauty and the Beast (1991)   
8246   0.203504  0.068453  2.972889     8961      Incredibles, The (2004)   
359    0.253411  0.085764  2.954762      364        Lion King, The (1994)   

                                                 genres  \
0           Adventure|Animation|Children|Comedy|Fantasy   
3021        Adventure|Animation|Children|Comedy|Fantasy   
2264                Adventure|Animation|Children|Comedy   
14813  Adventure|Animation|Children|Comedy|Fantasy|IMAX   
4780        Adventure|Animation|Children|Comedy|Fantasy   
580         Adventure|Animation|Children|Comedy|Musical   
6258                Adventure|Animation|Children|Comedy   
587     Animation|Children|Fantasy|Musical|Romance|IMAX   
8246         Action|Adventure|Animation|Children|Comedy   
359     Adventure|Animation|Children|Drama|Musical|IMAX   

                     clean_title  
0                 Toy Story 1995  
3021            Toy Story 2 1999  
2264            Bugs Life A 1998  
14813           Toy Story 3 2010  
4780           Monsters Inc 2001  
580                 Aladdin 1992  
6258           Finding Nemo 2003  
587    Beauty and the Beast 1991  
8246        Incredibles The 2004  
359           Lion King The 1994

In [ ]:
def find_similar_movies(movie_id):
  similar_users= ratings[(ratings["movieId"] == movie_id) & (ratings["rating"] > 4)]["userId"].unique()
  similar_users_rec= ratings[(ratings["userId"].isin(similar_users)) & (ratings["rating"] > 4)]["movieId"]

  similar_user_recs=similar_users_rec.value_counts()/len(similar_users)
  similar_user_recs=similar_user_recs[similar_user_recs > .1]

  all_users = ratings[(ratings["movieId"].isin(similar_user_recs.index)) & (ratings["rating"] > 4)]
  all_users_recs=all_users["movieId"].value_counts()/len(all_users["userId"].unique())

  recs_percentages=pd.concat([similar_user_recs, all_users_recs], axis=1)
  recs_percentages.columns=["similar","all"]

  recs_percentages["score"]=recs_percentages["similar"]/recs_percentages["all"]

  recs_percentages =recs_percentages.sort_values("score", ascending=False)
  return recs_percentages.head(10).merge(movies,left_index=True,right_on="movieId")[["score","title","genres"]]
  


In [ ]:
movie_name_input = widgets.Text(
    value='Toy Story',
    description='Movie Title:',
    disabled=False
)
recommendation_list = widgets.Output()

def on_type(data):
    with recommendation_list:
        recommendation_list.clear_output()
        title = data["new"]
        if len(title) > 5:
            results = search(title)
            movie_id = results.iloc[0]["movieId"]
            display(find_similar_movies(movie_id))

movie_name_input.observe(on_type, names='value')

display(movie_name_input, recommendation_list)

Text(value='Toy Story', description='Movie Title:')

Output()